name: nmail_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  enough_mail_plus: ^2.2.4
  flutter:
    sdk: flutter
  intl: ^0.20.2
  ndk: ^0.8.4-dev.5
  nostr_address_book: ^0.1.1
  path: ^1.9.1
  vcard_dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
