name: nmail_standard
description: "Everyone has an email address but nobody owns it. Nostr solves this."
publish_to: 'none'
version: 0.14.2+26

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  nmail_core: ^0.0.1
  flutter:
    sdk: flutter
  get: ^4.7.3
  firebase_messaging: ^16.4.1
  firebase_core: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "icons/web/icon-512.png"

flutter:
  uses-material-design: true
  assets:
    - icons/original_transparent_2x.svg
    - icons/original_transparent_3x.png
    - icons/github.svg
